import { ENV } from './env';

export const APP_NAME =
  ENV.APP_NAME;

export const FREE_PAGE_LIMIT =
  ENV.FREE_PAGE_LIMIT;

export const OCR_LANGUAGE =
  ENV.OCR_LANGUAGE;

export const DEFAULT_SPLIT_MODE =
  ENV.DEFAULT_SPLIT_MODE;

export const MAX_FILE_MB =
  ENV.MAX_FILE_MB;

export const PDF_RENDER_SCALE =
  ENV.PDF_RENDER_SCALE;

export const PDF_PREVIEW_SCALE =
  ENV.PDF_PREVIEW_SCALE;

export const ENABLE_OCR =
  ENV.ENABLE_OCR;

export const POSTHOG_KEY =
  ENV.POSTHOG_KEY;

export const SENTRY_DSN =
  ENV.SENTRY_DSN;

  export const SUPABASE_URL =
  ENV.SUPABASE_URL;

export const SUPABASE_ANON_KEY =
  ENV.SUPABASE_ANON_KEY;

export const FREE_MONTHLY_PAGE_LIMIT =
  ENV.FREE_MONTHLY_PAGE_LIMIT;

export const STRIPE_PUBLISHABLE_KEY =
  ENV.STRIPE_PUBLISHABLE_KEY;

export const STRIPE_PRICE_ID =
  ENV.STRIPE_PRICE_ID; 